Updated Package Dependencies & Resolved Deprecations
facebookresearch/ImageBind pull request #127
Opened 2024-11-03 16:44 UTC by sk5268

##  Replaced unnecessary import with appropriate class

`1`. in imagebind/data.py
- Instead of importing the entire module, only the `UniformTemporalSubsample` class was imported, as it was the only class needed.

## Replaced deprecated function:
   `2`. in imagebind/data.py:
- Changed `torchvision.transforms._transforms_video.NormalizeVideo` to `torchvision.transforms.transforms.Normalize`.

`3`. In imagebind/models/transformers.py file:
-  Changed `timm.models.layers` to `timm.layers`
 
 `4`. In imagebind/models/multimodal_preprocessors.py file:
 -  Changed `timm.models.layers` to `timm.layers`.

2024-11-03 16:47 UTC, sk5268 reviewed
Works out of the box with latest versions of package in requirements,txt
No specific version of packages necessary.

2024-11-19 04:03 UTC, sk5268 commented
@rohitgirdhar 
@ChrisjanWust

2024-11-22 04:23 UTC, sk5268 commented
@ChrisjanWust 
@rohitgirdhar
@msaroufim 
@aelnouby

2024-12-04 08:43 UTC, ChrisjanWust requested changes

2024-12-04 08:43 UTC, ChrisjanWust commented on imagebind/data.py
> +from torchvision.transforms.transforms import Normalize
These imported names will now raise a NameError further down. Please test with video.

2024-12-04 08:43 UTC, ChrisjanWust commented
Looks like these will break video input because of name errors. Please test with video next time.

2024-12-04 08:50 UTC, closed without merging